---
title: "ECE 4624: Meeting 8"
subtitle: "DT Fourier Series and Fourier Transform"
date: last-modified
author:
  - name: Chris Wyatt
    email: clwyatt@vt.edu
    affiliations: ECE@Virginia Tech

format: 
  revealjs:
    self-contained: false
    slide-number: true
    default-image-extension: svg
    theme: 
      - clw-slide-style.scss
    footer: "[ECE 4624: DSP and Filter Design](index.qmd)"
    
  html:
    default-image-extension: svg
    output-file: lecture-08-notes.html
    toc: false
    echo: false
    format-links: false

  beamer:
    default-image-extension: pdf
    output-file: lecture-08-slides.pdf
    fontsize: 10pt

html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"    
---

## {.t}

Today we will review the Fourier representation of DT signals and Fourier analysis of stable DT systems.

READING:

* PM 4.3 - 4.5
* ECE 2714 Supplementary Notes Chapters 15 and 17 

Topics:

- DT Fourier Series / Discrete Fourier Transform
- DT Fourier Transform
- Frequency Domain Analysis of DT systems

## {.t}

A DT signal $x[n]$ is periodic if $x[n] = x[n+kN]$ for integer
multiple $k$ and fundamental period $N \in \mathbb{Z}$.

- the fundamental frequency is $\omega_0 = \frac{2\pi}{N}$ rad/sec

## {.t}

When $x[n]$ is periodic the complex base of the Eigenfunction becomes
$z_k = e^{jk\omega_0}$, and the decomposition is a finite sum.

This gives the input-output relationship for a stable DT LTI system as

$$
x[n] = \sum\limits_{k = N_0}^{N_0 + N-1} a_k e^{jk\omega_0n} \;\longrightarrow\;  y[n] = \sum\limits_{k = N_0}^{N_0 + N-1} H\left(e^{j k\omega_0}\right) a_k e^{jk\omega_0 n}
$$
where $H\left(e^{j k\omega_0}\right)$ are the Eigenvalues or DT frequency response.

## Fourier Series Synthesis Equation {.t}

$$
x[n] = \sum\limits_{k = N_0}^{N_0 + N-1} a_k e^{jk\omega_0n}
$$

- the $a_k$ are the Fourier series coefficients


## Fourier Series Analysis Equation {.t}

$$
a_k = \frac{1}{N} \sum\limits_{n = N_0}^{N_0+N-1} x[n]e^{-j\frac{2\pi}{N} k n }
$$

::: notes

Note the coefficients themselves are periodic in $k$, with period $N$ and can be viewed as a discrete-frequency signal.

This is only one of three ways we can find the Fourier Series coefficients.

:::

## Finding the Fourier series coefficients using linear algebra {.t}

\begin{align*}
  x[N_0] &= \sum\limits_{k = N_0}^{N_0 + N-1} a_k e^{jk\omega_0N_0}\\
  x[N_0+1] &= \sum\limits_{k = N_0}^{N_0 + N-1} a_k e^{jk\omega_0(N_0+1)}\\
  \vdots\hspace{2em} &= \hspace{2em}\vdots\\
  x[N_0+N-1] &= \sum\limits_{k = N_0}^{N_0 + N-1} a_k e^{jk\omega_0(N_0+N-1)}\\
\end{align*}


::: notes
Another approach to find the coefficients $a_k$ is to note that there are a
finite number of terms in the summation and the signal has a finite
number of values over one period. This gives a system of $N$ linear
equations in $N$ unknowns (the $a_k$'s) which can be solved to find the coefficients using
linear algebra.
:::

## Relationship between Fourier series coefficients and Discrete Fourier Transform

Given a finite-length sequence of real or complex numbers $x[n]$, indexed from $0$ to $N-1$, the \emph{Discrete Fourier Transform} or DFT is given by
$$
X[k] = \sum_{n = 0}^{N-1}  x[n] e^{-j \frac{2\pi}{N}k n}
$$
for $k = 0, 1, 2, \cdots, N-1$. When $N$ is a power of 2, an efficient algorithm to compute this result exists and is called the \emph{Fast Fourier Transform} or FFT.

Note the similarity to the DT Fourier Series when $N_0 = 0$
$$
a_k = \frac{1}{N}\sum\limits_{n = N_0}^{N_0 + N - 1} x[n] e^{-j\frac{2\pi}{N}kn} =  \frac{1}{N}\sum\limits_{n = 0}^{N - 1} x[n] e^{-j\frac{2\pi}{N}kn} = \frac{1}{N} X[k]
$$

::: notes
The computation of the Fourier series coefficents and the Discrete Fourier Transform of a finite length signal are the same up to a constant. This gives yet another approach to finding the $a_k$'s that is very efficient via the FFT.
:::

## Spectrum {.t}

- a plot of $|a_k|$ versus $k$ is called the amplitude spectrum
- a plot of $\angle a_k$ versus $k$ is called the phase spectrum
- together they are just the spectrum
- a plot of $|a_k|^2$ versus $k$ is called the power spectrum

::: notes

The sum of all the terms in the power spectrum, by Parsevals theorem, is the Power of the DT signal.

:::

## Properties of the DT Fourier Series

Given two signals $x[n]$ and $y[n]$ periodic in $N$ with
$\omega_0 = \frac{2\pi}{N}$, having DT Fourier coefficients $a_k$ and
$b_k$ respectively.

- Linearity. The coefficients of the signal
  $$z[n] = Ax[n] + By[n] \mbox{ for constants } A,B$$ are $Aa_k + Bb_k$

- Index Shifting. The coefficients of
  $$z[n] = x[n-n_0] \mbox{ are } e^{-jk\omega_0 n_0}a_k$$ that is, it
  adds a phase shift.

- Frequency Shift. The coefficients of
  $$z[n] = x[n]e^{jm\omega_0n} \mbox{ are } a_{k-m}$$

- Index Reversal. The coefficients of
  $$z[n] = x[-n] \mbox{ are } a_{-k}$$


## Properties of the DT Fourier Series

- Multiplication. The coefficients of
  $$z[n] = x[n] \cdot y[n] \mbox{ are } \sum\limits_{m = N_0}^{N_0 + N -1} a_m\cdot b_{k-m}$$
  the discrete convolution of the individual signals' coefficients.

- Convolution. The coefficients of
  $$z[n] = x[n] * y[n] \mbox{ are } N a_k b_k$$

- Conjugate Symmetry. The coefficients of
  $$z[n] = x^*[n] = \Re{x[n]} - j\Im{x[n]} \mbox{ are } a_{-k}^*$$ A
  consequence of this property is that real, even signals have real,
  even $a_k$; and real, odd signals have purely imaginary, odd $a_k$.
  Thus if $x[n]$ is real $|a_k|$ is an even periodic function of $k$ and
  $\angle a_k$ is an odd periodic function of $k$.

## Properties of the DT Fourier Series {.t}

- Parseval's Relation. The power of the signal with Fourier series
  coefficients is
  $$\frac{1}{N} \sum\limits_{n = N_0}^{N_0 + N -1} |x[n]|^2\;dt = \sum\limits_{k = N_0}^{N_0+N-1} |a_k|^2$$

## DT Fourier Transform

* Recall the complex exponential $z^{n}$ for $z\in\mathbb{C}$ is the Eigenfunction of DT LTI systems. If we can decompose an input into a sum of such signals, we can easily determine the output using the superposition principle. We consider such a decomposition when the input is now aperiodic, called the DT Fourier Transform (DTFT).

* In contrast to the DT Fourier series, in this case the complex exponent of the Eigenfunction becomes $z = e^{j\omega}$ a continuous variable, and the decomposition is an uncountably infinite sum (integral). This gives the input-output relationship for a stable DT LTI system as

$$
x[n] = \frac{1}{2\pi}\int\limits_{2\pi} X\left(e^{j\omega}\right) \, e^{j \omega n}\; d\omega \;\longrightarrow\; y[n] = \frac{1}{2\pi}\int\limits_{2\pi} H\left(e^{j\omega}\right) X\left(e^{j\omega}\right) \, e^{j \omega n}\; d\omega
$$

where $H\left(e^{j \omega}\right)$ are the Eigenvalues, again called the \emph{frequency response}.

::: notes

The notation $X\left(e^{j\omega}\right)$ can be confusing. It just emphasizes that $z \rightarrow e^{j\omega}$. The expressions are functions of the independent variable $\omega$.

:::
